version: "3.0"
services:
 db:
  image: database
  container_name: db
  command: --init-file /data/application/init.sql
  volumes:
   - './src/db:/var/lib/mysql'
  ports:
   - '3308:3306'
  environment:
   MYSQL_ROOT_PASSWORD: password
   MYSQL_DATABASE: mydb1
   MYSQL_USER: user
   MYSQL_PASSWORD: password
  restart: always
 server:
  image: server
  ports:
   - "8000:80"
  container_name: server
  volumes:
   - './src:/var/www/html'
  depends_on:
   - db
 client:
  image: client
  container_name: client

